### ISSUE TITLE
Improve Action Button Names

### ISSUE THREAD

**Issue by landlessness** [zettaios/zetta#13]
In the `Hue Bulb Carl` display in the iOS app, the buttons are labeled `Go`. That turns out to be monotonous and not very informative. Instead, let's mimic the browser behavior and have the name of the action appear on the button. Screenshots attached.

![img_1383](https://cloud.githubusercontent.com/assets/21422/13293578/3218f1d6-daee-11e5-8f2b-cd2d7cca568c.PNG)
![screen shot 2016-02-24 at 11 56 04 am](https://cloud.githubusercontent.com/assets/21422/13293580/322b1848-daee-11e5-946b-49b4150a3109.png)

**Comment by benpackard** [comment]
Sounds good. Potential risk: field+button both with longer names (e.g. brightness) might get a bit cramped.
