### ISSUE TITLE
Add Google analytics

### ISSUE THREAD

**Issue by benpackard** [zettaios/zetta#2]
@chadalderson to provide account info/UA number

**Comment by chadalderson** [comment]
An update here. Request is out to Brian F. they are working on getting us the account set up. I'll be admin on that and can add @benpackard and @landlessness soon as it is ready.

In terms of capturing actions, etc. it would be nice to know which device in the list is getting the most play, other than that the vanilla analytics that come with the GA SDK are fine.

**Comment by chadalderson** [comment]
@benpackard here's the tracking info:

Tracking ID: 

UA-4084158-27

iOS SDK:

https://developers.google.com/analytics/devguides/collection/ios/v3/?ver=swift

**Comment by benpackard** [comment]
@chadalderson I'm blocked on this one since I can't create the configuration file. The apps list doesn't include Zetta even though I have access to that property via the GA dashboard. Who owns the analytics account? Perhaps they can create the config file as per https://developers.google.com/analytics/devguides/collection/ios/v3/?ver=swift and send it to me?

I'm attaching the screen in question for reference. The first select box is where I would normally see the existing property listed.

![screen shot 2016-02-25 at 12 35 25 pm](https://cloud.githubusercontent.com/assets/2280914/13328407/74a49a7c-dbbc-11e5-89ea-f8317e61cf3e.png)

**Comment by chadalderson** [comment]
Escalated this to Morgan - (see email Ben)

_Chad Alderson_

_Owner, AMP.build_
_"No bull. Just build."_

Email: chad@amp.build
Phone: 408.761.9000 <1-408-761-9000>
http://amp.build | schedule a meeting
https://calendly.com/chadalderson/15min | Instagram
http://www.instagram.com/amp.build

**Comment by benpackard** [comment]
Added and custom tracking for device type working.
![screen shot 2016-02-27 at 10 22 53 am](https://cloud.githubusercontent.com/assets/2280914/13373920/ac093004-dd42-11e5-8bee-b932c91bb260.png)
