### ISSUE TITLE
map foregroundColor & backgroundColor to UI buttons

### ISSUE THREAD

**Issue by landlessness** [zettaios/zetta#27]
In the attached screenshot I expected the button text color to be green.

(i'm guessing you didn't get there yet, @benpackard, but just wanted an issue to track it.)

![img_1628](https://cloud.githubusercontent.com/assets/21422/13902481/a0f700c6-ee20-11e5-8dc1-dcf0b9b18a86.PNG)

**Comment by benpackard** [comment]
This is in the next build.
