### ISSUE TITLE
Apply server style colors to server header in device list

### ISSUE THREAD

**Issue by landlessness** [zettaios/zetta#32]
Let's have the color information applied to the server header in the device list. For example, in the attached screen shot, the `sanjose` row should have a white box, white text and a blue-gray background and the `bangalore` row should have a white box, white text and a lime-green background to match the devices in the list.

![img_3469](https://cloud.githubusercontent.com/assets/21422/16791389/70d54c74-488c-11e6-8b42-678f170ad1a2.PNG)

**Comment by benpackard** [comment]
Processing via TestFlight and should be with you shortly. Will need pushing out by your guys to the App Store once approved. Thanks.

**Comment by landlessness** [comment]
thanks @benpackard. i have it on my phone. it looks great.
