### ISSUE TITLE
Add brand color to metadata API

### ISSUE THREAD

**Issue by benpackard** [zettaios/zetta#4]
This would be a single set of r/g/b values at the top-level to use as a tint color on iOS labels and buttons throughout the app.

**Comment by chadalderson** [comment]
@benpackard - so you have a sense for what we are thinking with this approach:

![ui](https://cloud.githubusercontent.com/assets/4534002/13264544/8a02ffc0-da23-11e5-9efc-2fcfee6d8a23.png)

And

![brand-concept](https://cloud.githubusercontent.com/assets/4534002/13264565/a409bc9c-da23-11e5-968c-868c2ea7afcf.png)

**Comment by benpackard** [comment]
@landlessness Going to self-assign this one now since the values are in the API.

**Comment by landlessness** [comment]
cool

**Comment by benpackard** [comment]
For now the primary brand color is used sparingly on both the server's grouping title and for certain controls (e.g. buttons) on devices for that server. I think there is more that could be done with these but its a good first step. We can also easily support state-image colors using a similar approach (e.g. red locked door, blue bulb).
