### ISSUE TITLE
Add device icon to metadata

### ISSUE THREAD

**Issue by benpackard** [zettaios/zetta#5]
Phase I is simply a pre-device URI from which to download the icon.

**Comment by chadalderson** [comment]
@benpackard you mentioned needing a new icon here. Can you drop the specs below? We will get on that.

**Comment by benpackard** [comment]
I don't think so, this one is just the device icon URL that @landlessness is adding to the API. I do need the 1024 png version of the app icon, but that's in a different issue I think.

**Comment by chadalderson** [comment]
Cool - here you go.

![zettalogo1024](https://cloud.githubusercontent.com/assets/4534002/13265766/937683a0-da29-11e5-852f-b5005836e169.png)
